name: CI


on:
    push:
      branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm start &
      - run: npx newman run tests/SOS2021-28-awards.postman_collection.json 
      - run: npx newman run tests/SOS2021-28-platforms.postman_collection.json
      - run: npx newman run tests/SOS2021-28-games.postman_collection.json
